### ISSUE TITLE
Error from QRCode draw

### ISSUE THREAD

**Issue by samohtroh** [nayuki/QR-Code-generator#147]
suddenly  I run in following error:

Exception in thread "main" java.lang.NoSuchMethodError: 'io.nayuki.qrcodegen.QrCode io.nayuki.qrcodegen.QrCode.encodeText(java.lang.String, io.nayuki.qrcodegen.QrCode$Ecc)'
	at net.codecrete.qrbill.generator.QRCode.draw(QRCode.java:49)
	at net.codecrete.qrbill.generator.BillLayout.drawPaymentPart(BillLayout.java:137)
	at net.codecrete.qrbill.generator.BillLayout.draw(BillLayout.java:99)
	at net.codecrete.qrbill.generator.QRBill.validateAndGenerate(QRBill.java:213)
	at net.codecrete.qrbill.generator.QRBill.generate(QRBill.java:129)
	at net.codecrete.qrbill.examples.QRBillExample.main(QRBillExample.java:119)

as I restore all code changes I made and have still get the same error I'm wondering if the error are cased by changes in io.nayuki.qrcodegen.QrCode?

I'm using gradle

**Comment by manuelbl** [comment]
This error is caused because the SwissQRBill library used a version range and the QR-Code-generator project released a new version violating [semver](https://semver.org/) versioning.

Please upgrade to the lasted version of SwissQRBill library.

Also see https://github.com/manuelbl/SwissQRBill/issues/60

**Comment by samohtroh** [comment]
Thanks for the hint it helped
