### ISSUE TITLE
heap-buffer-overflow in the C implementation

### ISSUE THREAD

**Issue by dende** [nayuki/QR-Code-generator#78]
I set up fuzzing for the project and quickly found a heap-buffer-overflow in the c implementation.

The fuzz target I wrote: 
```C
#include <stdbool.h>
#include <stdint.h>
#include "qrcodegen.h"

#ifdef __cplusplus
extern "C" {
#endif

int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {

  uint8_t qr0[qrcodegen_BUFFER_LEN_MAX];
  bool ok = qrcodegen_encodeBinary((uint8_t *) Data, Size, qr0, qrcodegen_Ecc_MEDIUM, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_4, true);
  if (!ok)
      return 1;

  return 0;
}

#ifdef __cplusplus
}
#endif
```

The ouput generated by libFuzzer and Address Sanitizer: 
```
==11==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000091 at pc 0x00000055c694 bp 0x7ffcd6876f30 sp 0x7ffcd6876f28
WRITE of size 1 at 0x602000000091 thread T0
SCARINESS: 31 (1-byte-write-heap-buffer-overflow)
    #0 0x55c693 in addEccAndInterleave /src/libqrcodegen/c/qrcodegen.c:316:14
    #1 0x55c693 in qrcodegen_encodeSegmentsAdvanced /src/libqrcodegen/c/qrcodegen.c:259:2
    #2 0x55e43f in qrcodegen_encodeBinary /src/libqrcodegen/c/qrcodegen.c:179:9
    #3 0x55413d in LLVMFuzzerTestOneInput /src/libqrcodegen/c/encodeBinary_fuzzer.c:12:13
    #4 0x459d61 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
    #5 0x45bc65 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:743:3
    #6 0x45c229 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:792:3
    #7 0x44a638 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:824:6
    #8 0x474462 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #9 0x7efcb09d482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x41dcf8 in _start (/out/encodeBinary_fuzzer+0x41dcf8)

0x602000000091 is located 0 bytes to the right of 1-byte region [0x602000000090,0x602000000091)
allocated by thread T0 here:
    #0 0x5218fd in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x432b67 in operator new(unsigned long) (/out/encodeBinary_fuzzer+0x432b67)
    #2 0x45bc65 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:743:3
    #3 0x45c229 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:792:3
    #4 0x44a638 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:824:6
    #5 0x474462 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #6 0x7efcb09d482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/libqrcodegen/c/qrcodegen.c:316:14 in addEccAndInterleave
Shadow bytes around the buggy address:
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff8000: fa fa 00 00 fa fa 00 fa fa fa 00 fa fa fa 00 fa
=>0x0c047fff8010: fa fa[01]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==11==ABORTING
MS: 0 ; base unit: 0000000000000000000000000000000000000000
```

This bug is being triggered, with zero-length input, but it also occured when forcing the fuzzer to use bigger inputs (eg. putting `if (Size < 40) return 0;` as the first line.

**Comment by nayuki** [comment]
I'm pretty sure your code example is invalid because you failed to meet the preconditions:

    /* 
     * Encodes the given binary data to a QR Code, returning true if encoding succeeded.
     * If the data is too long to fit in any version in the given range
     * at the given ECC level, then false is returned.
     * - The input array range dataAndTemp[0 : dataLen] should normally be
     *   valid UTF-8 text, but is not required by the QR Code standard.
     * - The variables ecl and mask must correspond to enum constant values.
     * - Requires 1 <= minVersion <= maxVersion <= 40.
     * 
     * - The arrays dataAndTemp and qrcode must each have a length <-- !!!
     *   of at least qrcodegen_BUFFER_LEN_FOR_VERSION(maxVersion). <-- !!!
     * 
     * - After the function returns, the contents of dataAndTemp may have changed,
     *   and does not represent useful data anymore.
     * - If successful, the resulting QR Code will use byte mode to encode the data.
     * - In the most optimistic case, a QR Code at version 40 with low ECC can hold any byte
     *   sequence up to length 2953. This is the hard upper limit of the QR Code standard.
     * - Please consult the QR Code specification for information on
     *   data capacities per version, ECC level, and text encoding mode.
     */
    bool qrcodegen_encodeBinary(uint8_t dataAndTemp[], size_t dataLen, uint8_t qrcode[],
        enum qrcodegen_Ecc ecl, int minVersion, int maxVersion, enum qrcodegen_Mask mask, bool boostEcl);

I will concede that using this C library of mine correctly is inherently *not easy*. This is the price to pay because the library completely avoids heap allocations. So the caller must allocate (on the heap or stack) buffers that are **appropriately sized**.

**Comment by nayuki** [comment]
Here is a better fuzzer for my C library:

```c
int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
    if (Size < 2)
        return 0;
    enum qrcodegen_Ecc ecl = (enum qrcodegen_Ecc)(Data[0] % 4);
    int maxVersion = (Data[1] % 40) + 1;
    size_t bufLen = (size_t)qrcodegen_BUFFER_LEN_FOR_VERSION(maxVersion);
    
    Data += 2;
    Size -= 2;
    if (Size > bufLen)
        return 0;
    
    uint8_t *dataTemp = malloc(bufLen * sizeof(uint8_t));
    uint8_t *qrcode   = malloc(bufLen * sizeof(uint8_t));
    memcpy(dataTemp, Data, Size * sizeof(uint8_t));
    
    bool ok = qrcodegen_encodeBinary(dataTemp, Size, qrcode, ecl,
        qrcodegen_VERSION_MIN, maxVersion, qrcodegen_Mask_AUTO, false);
    
    free(dataTemp);
    free(qrcode);
    return 0;
}
```
