### ISSUE TITLE
global-buffer-overflow in the C++ implementation

### ISSUE THREAD

**Issue by dende** [nayuki/QR-Code-generator#81]
The following fuzz target finds a global-buffer-overflow in the C++ implementation:
```C++
#include <cstdlib>
#include "QrCode.hpp"


extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
  if (Size < 2) {
    return 0;
  }

  auto ecc_byte = (int) Data[0];
  Data++;Size--;


  std::vector<uint8_t> dataVector(Data, Data + Size);
  qrcodegen::QrCode::Ecc ecl = static_cast<qrcodegen::QrCode::Ecc> (ecc_byte % 5);
  auto qr = qrcodegen::QrCode::encodeBinary(dataVector, ecl);

  return 0;
}
```
The first byte of the random input is used to randomize the error correction level.

```
==11==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000006011a5 at pc 0x00000055c719 bp 0x7fff9fa774f0 sp 0x7fff9fa774e8
READ of size 1 at 0x0000006011a5 thread T0
SCARINESS: 12 (1-byte-read-global-buffer-overflow)
    #0 0x55c718 in getNumDataCodewords /src/libqrcodegen/cpp/QrCode.cpp:733:5
    #1 0x55c718 in qrcodegen::QrCode::encodeSegments(std::__1::vector<qrcodegen::QrSegment, std::__1::allocator<qrcodegen::QrSegment> > const&, qrcodegen::QrCode::Ecc, int, int, int, bool) /src/libqrcodegen/cpp/QrCode.cpp:263:26
    #2 0x55d365 in qrcodegen::QrCode::encodeBinary(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, qrcodegen::QrCode::Ecc) /src/libqrcodegen/cpp/QrCode.cpp:251:9
    #3 0x554ff4 in LLVMFuzzerTestOneInput /src/encode_binary_cpp_fuzzer.cpp:14:13
    #4 0x45aba1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
    #5 0x45a2c5 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:470:3
    #6 0x45c667 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:698:19
    #7 0x45d3f5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:830:5
    #8 0x44b478 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:824:6
    #9 0x4752a2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #10 0x7fdb36a0582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #11 0x41eb38 in _start (/out/encode_binary_cpp_fuzzer+0x41eb38)

0x0000006011a5 is located 59 bytes to the left of global variable '<string literal>' defined in 'QrCode.cpp:717:27' (0x6011e0) of size 28
  '<string literal>' is ascii string 'Version number out of range'
0x0000006011a5 is located 1 bytes to the right of global variable 'qrcodegen::QrCode::ECC_CODEWORDS_PER_BLOCK' defined in 'QrCode.cpp:829:22' (0x601100) of size 164
SUMMARY: AddressSanitizer: global-buffer-overflow /src/libqrcodegen/cpp/QrCode.cpp:733:5 in getNumDataCodewords
```

**Comment by nayuki** [comment]
Can you please clarify your test case to only use constants? It is not obvious to me how to assign values to `Data` and `Size` in your function in order to trigger an array overflow in my library.

**Comment by nayuki** [comment]
Upon closer inspection, your example code is invalid because of:

    qrcodegen::QrCode::Ecc ecl = static_cast<qrcodegen::QrCode::Ecc> (ecc_byte % 5);

Casting from int to enum is a code smell. More concretely, `enum Ecc` has not 5 members, but exactly 4:

    public: enum class Ecc {
        LOW = 0 ,  // The QR Code can tolerate about  7% erroneous codewords
        MEDIUM  ,  // The QR Code can tolerate about 15% erroneous codewords
        QUARTILE,  // The QR Code can tolerate about 25% erroneous codewords
        HIGH    ,  // The QR Code can tolerate about 30% erroneous codewords
    };

**Comment by dende** [comment]
You are correct, I messed up the cast :+1: 

Casting this int to enum might be a code smell, but if done correctly (which I did not do) it is a very useful tool to take a single byte of the fuzzer-generated random data and randomize enums. 

With the cast in the correct range (%4)  the cpp fuzzer runs happily without crashing!
